### ISSUE TITLE
Не обрабатывать IndexOutOfBoundsException таким образом

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#13]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-client/src/main/java/com/alan/lab/client/Client.java#L29

**Comment by AlphaBeth** [comment]
Для проверки того, что в массиве/коллекции достаточно элементов, есть более правильные способы

**Comment by lm-cyber** [comment]
готово
