### ISSUE TITLE
В какой ситуации возникает это исключение?

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#17]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-client/src/main/java/com/alan/lab/client/ConsoleClient.java#L120

В try огромный блок кода, в любом месте может возникнуть это исключение. Явно нужно уменьшить область обработки этого исключения.

**Comment by lm-cyber** [comment]
исправил кидает parseToNameAndArg
