### ISSUE TITLE
В ответе возвращать не только строчку

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#18]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-common/src/main/java/com/alan/lab/common/network/Response.java#L5

Какие-то команды возвращают просто сообщение. Другие - коллекцию ваших объектов (show, например). average_of_height - число, history - массив строк, и так далее.

**Comment by lm-cyber** [comment]
готово
