### ISSUE TITLE
Класс не используется

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#19]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-common/src/main/java/com/alan/lab/common/utility/HistoryManager.java#L7

**Comment by AlphaBeth** [comment]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-common/src/main/java/com/alan/lab/common/utility/CollectionManager.java#L14

**Comment by AlphaBeth** [comment]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-common/src/main/java/com/alan/lab/common/utility/FileManager.java#L8

**Comment by lm-cyber** [comment]
не правда
