### ISSUE TITLE
На сервере по заданию используется блокирующий ввод/вывод через сокет и потоки ввода/вывода

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#20]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-server/src/main/java/com/alan/lab/server/ObjectSocketWrapper.java#L12

**Comment by lm-cyber** [comment]
изменил

**Comment by lm-cyber** [comment]
готов
