### ISSUE TITLE
Реализация не соответствует принципам SOLID, особенно Open-Closed и Single responsibility

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#22]
https://github.com/lm-cyber/lab6_arhitip/blob/99d79cf84865e8595cf30b36544ea887df204266/lab-server/src/main/java/com/alan/lab/server/ResponseCreator.java#L73

При добавлении новой команды приходится переписывать метод, а не добавлять новые классы

**Comment by lm-cyber** [comment]
сделал
