### ISSUE TITLE
Добавить нормальное форматирование вывода, не использовать toString коллекций

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#23]

**Comment by lm-cyber** [comment]
какой например

**Comment by lm-cyber** [comment]
![image](https://user-images.githubusercontent.com/73221496/167251577-80a89bb1-eb8f-4d2c-aa8e-94abfe02a78b.png)

**Comment by lm-cyber** [comment]
![image](https://user-images.githubusercontent.com/73221496/167251595-728dd831-0cfc-4bf5-80fa-a52486fed340.png)

**Comment by AlphaBeth** [comment]
Тут лучше не использовать Integer.
