### ISSUE TITLE
Не "глотать" SQLException - пользователь должен знать, что что-то пошло не так при выполнении команды

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#28]

**Comment by lm-cyber** [comment]
готов

**Comment by AlphaBeth** [comment]
Не вижу. У вас просто возвращается true/false, причем false может даже без SQLException вернуться.

**Comment by lm-cyber** [comment]
![image](https://user-images.githubusercontent.com/73221496/175698929-d3cb1b7d-1998-41b5-93e7-d8f7ab836974.png)
