### ISSUE TITLE
CollectionManager не потокобезопасен

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#34]
Много непотокбезопасных полей

**Comment by lm-cyber** [comment]
![image](https://user-images.githubusercontent.com/73221496/175103501-d9783f90-d783-40a8-86c7-d76a867b661c.png)

**Comment by AlphaBeth** [comment]
Зачем ConcurrentSkipListSet? Это аналог TreeSet, но вам не нужна сортировка, достаточно уникальности. Используйте потокобезопасный аналог HashSet.

**Comment by lm-cyber** [comment]
![image](https://user-images.githubusercontent.com/73221496/175719872-510ae7bb-9efd-4e63-a277-f707a15cd21c.png)
