### ISSUE TITLE
Стоит создать простой класс с парой полей вместо непонятного массива.

### ISSUE THREAD

**Issue by AlphaBeth** [lm-cyber/lab6_arhitip#8]
https://github.com/lm-cyber/lab5_arhitip/blob/e462941d5f400acb59c21bff661a9d120af3f69d/lab-client/src/main/java/com/alan/lab/client/utility/Console.java#L42

**Comment by lm-cyber** [comment]
там просто деление на две части ,если это возможно

**Comment by AlphaBeth** [comment]
И всё равно это неочевидно. По какому индексу лежит название команды? Всегда по индексу 0? А может ли быть под индексом 1? А в массиве всегда не больше 2 элементов?

**Comment by AlphaBeth** [comment]
Выделить небольшой класс с двумя полями - это не сложно, а понимать код станет проще.
